trigger:
- feature/*
- main

pool: Default

variables:
  workDir: '$(System.DefaultWorkingDirectory)/environments/dev'

stages:

# 🔹 BUILD + PLAN
- stage: Build
  displayName: Build
  jobs:
  - job: TerraformInitPlan
    displayName: Terraform Init and Plan Job
    steps:

    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTask@5
      displayName: Terraform Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: $(workDir)
        backendServiceArm: 'pipelineserviceconn'
        backendAzureRmResourceGroupName: 'pipeline_rg'
        backendAzureRmStorageAccountName: 'pipelinestgac'
        backendAzureRmContainerName: 'pipelineblob'
        backendAzureRmKey: 'dev.terraform.tfstate'
        # backendAzureRmUseAzureAD: true  ❌ removed (403 fix)

    - task: TerraformTask@5
      displayName: Terraform Plan
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: $(workDir)
        environmentServiceNameAzureRM: 'pipelineserviceconn'


# 🔹 DEPLOY / APPLY
- stage: Deploy
  displayName: Terraform Apply
  condition: succeeded()

  jobs:
  - job: TerraformApply
    displayName: Terraform Apply Job
    pool: Default
    steps:

    - task: TerraformTask@5
      displayName: Terraform Init (Deploy)
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: $(workDir)
        backendServiceArm: 'pipelineserviceconn'
        backendAzureRmResourceGroupName: 'pipeline_rg'
        backendAzureRmStorageAccountName: 'pipelinestgac'
        backendAzureRmContainerName: 'pipelineblob'
        backendAzureRmKey: 'dev.terraform.tfstate'
        # backendAzureRmUseAzureAD: true ❌ removed

    - task: TerraformTask@5
      displayName: Terraform Apply
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: $(workDir)
        environmentServiceNameAzureRM: 'pipelineserviceconn'